### ISSUE TITLE
[Bug]: DTDL Command not supported

### ISSUE THREAD

**Issue by ridomin** [microsoft/dtdl-model-generator#11]
### Describe the bug

Trying to generate from models using DTDL command I got an exeception

### Which version of the tool was used?

latest

### Steps To Reproduce

I got the error below

```
Unhandled exception. System.Exception: Unsupported content type: Command
   at Microsoft.DigitalWorkplace.DigitalTwins.Models.Generator.ClassEntity.CreateProperty(DTContentInfo content) in C:\code\dtdl-model-generator\src\Generator\Base\ClassEntity.cs:line 74
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Microsoft.DigitalWorkplace.DigitalTwins.Models.Generator.ModelEntity..ctor(DTInterfaceInfo interfaceInfo, ModelGeneratorOptions options) in C:\code\dtdl-model-generator\src\Generator\Entity\ModelEntity.cs:line 20
   at Microsoft.DigitalWorkplace.DigitalTwins.Models.Generator.ModelGenerator.<GenerateModels>b__10_0(DTInterfaceInfo m) in C:\code\dtdl-model-generator\src\Generator\ModelGenerator.cs:line 80
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.DigitalWorkplace.DigitalTwins.Models.Generator.ModelGenerator.GenerateModels(IEnumerable`1 models) in C:\code\dtdl-model-generator\src\Generator\ModelGenerator.cs:line 81
   at Microsoft.DigitalWorkplace.DigitalTwins.Models.Generator.ModelGenerator.GenerateClassesAsync() in C:\code\dtdl-model-generator\src\Generator\ModelGenerator.cs:line 52
```

**Comment by ms-mikeb** [comment]
@ridomin Thank you for your issue. I'll be adjusting this Issue and changing it to a feature.

Not supporting commands isn't a bug, but rather an intentional exclusion. Our original thought was that since Azure Digital Twins did not currently use Commands, we would leave this out for now. That said, since we realize other products use DTDL, and thus supporting Commands would be useful. As such, we'll update our docs to better indicate what we do/don't support and why, as well as look at the timeline for when we could implement support for Commands. We'll also need to come up with a rough draft of what Commands would look like in C#.

Let me know if you have any questions/comments/concerns.

**Comment by ms-mikeb** [comment]
Closing this issue as we're tracking work to support Commands in [#12](https://github.com/microsoft/dtdl-model-generator/issues/12).
